import socket
import time

host = '127.0.0.1'
port = 8080

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

client_socket.settimeout(5)

try:
    client_socket.connect((host, port))
    print("Connection established!")
    
    message = "Hello, listener!BROKE BROKE BROKE BROKE BROKEBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKBROKE BROKE BROKE BROKE BROKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE "
    client_socket.sendall(message.encode())
    print("Data sent!")

except socket.timeout:
    print("Connection timed out.")
except socket.error as e:
    print(f"Connection failed: {e}")
finally:
    client_socket.close()

